/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Robson' at '10/02/16 09:10' with Gradle 2.9
 *
 * @author Robson, @date 10/02/16 09:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
